.nh
.TH "GWTT" "1" "Feb 2026" "gwtt" "Git Worktree Tasks Manual"

.SH NAME
gwtt-apply - Apply changes between a Codex worktree and the local checkout


.SH SYNOPSIS
\fBgwtt apply <task> [flags]\fP


.SH DESCRIPTION
Apply changes between a Codex worktree and the local checkout


.SH OPTIONS
\fB--dry-run\fP[=false]
	show git commands without executing

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for apply

.PP
\fB--yes\fP[=false]
	skip confirmation prompts


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--mode\fP="classic"
	execution mode: classic or codex

.PP
\fB--nocolor\fP[=false]
	disable color output

.PP
\fB--theme\fP="default"
	color theme: default, dracula, gruvbox, nord, solarized

.PP
\fB--themes\fP[=false]
	print available themes and exit


.SH SEE ALSO
\fBgwtt(1)\fP
