.nh
.TH "GWTT" "1" "Jan 2026" "gwtt" "Git Worktree Tasks Manual"

.SH NAME
gwtt-create - Create a worktree and branch for a task


.SH SYNOPSIS
\fBgwtt create  [flags]\fP


.SH DESCRIPTION
Create a worktree and branch for a task


.SH OPTIONS
\fB--base\fP=""
	base branch to create from (default: current branch)

.PP
\fB--dry-run\fP[=false]
	show git commands without executing

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB-o\fP, \fB--output\fP="text"
	output format: text or raw

.PP
\fB-p\fP, \fB--path\fP=""
	override worktree path (relative to repo root or absolute)

.PP
\fB--skip\fP[=false]
	alias for --skip-existing

.PP
\fB--skip-existing\fP[=false]
	reuse an existing worktree path if present


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--nocolor\fP[=false]
	disable color output

.PP
\fB--theme\fP="default"
	color theme: default, dracula, gruvbox, nord, solarized

.PP
\fB--themes\fP[=false]
	print available themes and exit


.SH SEE ALSO
\fBgwtt(1)\fP
