.nh
.TH "GWTT" "1" "Feb 2026" "gwtt" "Git Worktree Tasks Manual"

.SH NAME
gwtt - Task-based git worktree helper


.SH SYNOPSIS
\fBgwtt [flags]\fP


.SH DESCRIPTION
Create, manage, and clean up git worktrees based on task names.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for gwtt

.PP
\fB-m\fP, \fB--mode\fP="classic"
	execution mode: classic or codex

.PP
\fB--nocolor\fP[=false]
	disable color output

.PP
\fB--theme\fP="default"
	color theme: default, dracula, gruvbox, nord, solarized

.PP
\fB--themes\fP[=false]
	print available themes and exit


.SH SEE ALSO
\fBgwtt-apply(1)\fP, \fBgwtt-cleanup(1)\fP, \fBgwtt-create(1)\fP, \fBgwtt-finish(1)\fP, \fBgwtt-list(1)\fP, \fBgwtt-overwrite(1)\fP, \fBgwtt-status(1)\fP
